name: build mac os
on: [push]
jobs:
  build:
    name: Build MacOS
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.25.x'

      - name: cmake cache
        run: cmake . -DCMAKE_BUILD_TYPE="Debug"
        working-directory: src/

      - name: cmake build
        run: cmake --build . --clean-first
        working-directory: src/
