name: Build Emscripten
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Emscripten SDK
        uses: mymindstorm/setup-emsdk@v11

      - name: Check Emscripten version
        run: emcc -v

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.26.x'

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -t src/deps

      - name: create cmake cache debug using emscripten (emcmake)
        run: emcmake cmake -B build/emscripten-debug -DMAKE_WASM_BUILD=ON -DCMAKE_BUILD_TYPE=Debug
        working-directory: src

      - name: create cmake cache release using emscripten (emcmake)
        run: emcmake cmake -B build/emscripten-release -DMAKE_WASM_BUILD=ON
        working-directory: src

      - name: build debug
        run: cmake --build build/emscripten-debug
        working-directory: src

      - name: build release
        run: cmake --build build/emscripten-release --clean-first
        working-directory: src

      - name: build debug again
        run: cmake --build build/emscripten-debug --clean-first
        working-directory: src

      - uses: actions/upload-artifact@v3.1.2
        with:
          name: Secure Random Emscripten Library
          path: |
            src/lib/libsecure-random.a
